# Generated by Django 3.1.2 on 2020-10-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abs_path', models.CharField(max_length=100, unique=True)),
                ('img_url', models.CharField(max_length=100)),
                ('video_url', models.CharField(max_length=100)),
                ('desc_url', models.CharField(max_length=100)),
                ('sub_json', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
