# Generated by Django 3.1.2 on 2020-11-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_db',
            name='desc_url',
        ),
        migrations.AddField(
            model_name='movie_db',
            name='descr',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='movie_db',
            name='img_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie_db',
            name='movie_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie_db',
            name='sub_json',
            field=models.CharField(default='[]', max_length=100),
        ),
    ]
