# Generated by Django 3.1.2 on 2020-10-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_db',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
