# Generated by Django 3.1.2 on 2020-11-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20201102_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_db',
            name='movie_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
