# Generated by Django 3.1.2 on 2020-10-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20201030_1443'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Movie_db',
        ),
    ]
