# Generated by Django 3.1.2 on 2020-10-30 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_auto_20201030_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_db',
            old_name='video_url',
            new_name='movie_url',
        ),
    ]
