# Generated by Django 3.1.2 on 2020-10-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_path', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('ext', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='User_db',
        ),
    ]
