# Generated by Django 3.1.2 on 2020-10-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_player', '0002_auto_20201030_1409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_db',
        ),
        migrations.DeleteModel(
            name='Video_File',
        ),
    ]
